### ISSUE TITLE
Start command should support passing Thin config file

### ISSUE THREAD

**Issue by kvedurmu** [paketo-buildpacks/thin#6]
Thin supports a server config file that can be generated via the `thin config` command. It would be great if the buildpack could support a user passing in a path to a Thin config file that gets set in the buildpack's start command (e.g `thin -C /path/to/config.yml -p PORT`)

**Comment by fg-j** [comment]
@paketo-buildpacks/ruby-maintainers Is this still a relevant feature request? Are there any blockers?

**Comment by sophiewigmore** [comment]
As far as I know, it's viable and there are no blockers. I believe this is a reasonable request, since it's use-case supported by Thin already.

**Comment by sophiewigmore** [comment]
@robdimsdale I think my preference would be to look for `thin.yml` as the default, and also allow for `BP_THIN_CONFIG_LOCATION`.
